name: Monthly builds

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-snapcrafts:
    name: Generate snapcraft.yaml files
    runs-on: [ubuntu-latest]
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Generate snapacraft yaml files for all ros distros
        id: generate
        run: |
          pip install .
          python3 ./generate_all_ros_meta_snapcraft_file.py
          echo "matrix=$(ls snaps/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
      - name: Upload snapcrafts folders
        uses: actions/upload-artifact@v3
        with:
          name: snapcraft_yamls
          path: snaps/

  snaps:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    needs: generate-snapcrafts
    strategy:
      fail-fast: false
      matrix:
        snap_dir: ${{ fromJSON(needs.generate-snapcrafts.outputs.matrix) }}
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      snapcraft-source-subdir: ${{ matrix.snap_dir }}
      runs-on: '["ubuntu-latest", ["self-hosted", "linux", "X64", "medium", "noble"]]'
