name: Promote snaps

on:
  workflow_dispatch:

jobs:
  generate-snap-matrix:
    name: Generate snapcraft.yaml files
    runs-on: [ubuntu-latest]
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Generate snapacraft yaml files for all ros distros
        id: generate
        run: |
          pip install .
          python3 ./generate_all_ros_meta_snapcraft_file.py
          echo "matrix=$(ls snaps/ | sed -e 's/-[a-zA-Z0-9]*$//' | uniq | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  promote:
    runs-on: ubuntu-latest
    needs: [generate-snap-matrix]
    strategy:
      fail-fast: false
      matrix:
        snap_names: ${{ fromJSON(needs.generate-snap-matrix.outputs.matrix) }}
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
    steps:
      - name: Setup Snapcraft
        run: |
          sudo snap install snapcraft --classic
      - name: Promote ROS snaps to stable
        run: |
          snapcraft promote ros-${{ matrix.snap_names }} --from-channel latest/beta --to-channel latest/stable --yes
      - uses: actions/upload-artifact@v4
        name: Upload snapcraft logs
        if: always()
        with:
          name: snapcraft_logs_${{ matrix.snap_names }}
          path: |
            /home/runner/.local/state/snapcraft/log/

