name: Promote snaps

on:
  workflow_dispatch:

jobs:
  generate-snap-matrix:
    name: Generate snap matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6

      - name: Generate snapcraft yaml files for all ROS distros
        id: generate
        run: |
          pip install .
          python3 ./generate_all_ros_meta_snapcraft_file.py
          python3 ./generate_all_ros_esm_meta_snapcraft_file.py
          # List snap folders, exclude -dev variants, prefix with 'ros-' to match store names
          echo "matrix=$(ls snaps/ | grep -v '\-dev$' | sed 's/^/ros-/' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  promote:
    needs: [generate-snap-matrix]
    strategy:
      fail-fast: false
      matrix:
        snap: ${{ fromJSON(needs.generate-snap-matrix.outputs.matrix) }}
    uses: canonical/robotics-actions-workflows/.github/workflows/promote.yaml@main
    with:
      snap: ${{ matrix.snap }}
      from-channel: latest/beta
      to-channel: latest/stable
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
